### PR TITLE
Savings

### PR DESCRIPTION
**Pull request by troycomi**
This is working as far as I can tell, but I've only been running the garden for a few hours.  Consider this a WIP and request for feedback...

Some outstanding concerns:
- For the garden, I'm not sure I've grouped together cost calculations the most efficient way.
- It may be better to check the garden first if the goal is to maximize the number of sacrifices for sugar lumps
- I'm not sure if savings should be set to 0 before ascending or if it won't matter
- For the timing of savings, I have it start after 30 minutes which shouldn't interfere with neverclick or speed baking.  It then ramps up to hit the requirement for max lucky or lucky-frenzy over the course of 400 minutes.  This allows some purchasing while saving but can seem slow before getting hardcore.
- I'd welcome feedback on the code, I'm new to JS

### CODE REVIEW

**Comment by troycomi** [comment]
Cleaned up the garden code so it is working and played with the rescaling to hopefully work better for new games.

I ended up rebasing on master (hence the force push), sorry if someone else has worked on this since yesterday!

**Comment by PrinzAndreas** [comment]
I am not sure that I understand the idea behind. It seems you save for buying plants in one go instead of one by one. Is there more to it? It is also realted to buying buildings?
There is one trick that is used in buying buildings, that we buy 100 of each over though there are not as many we can buy. This makes the buying process after the ascend quicker. It is doen by the combination of checkAmount and buyAmount. It seems that you now check that the correct amount is available - that would not work too well after ascend, I think. See also the related [issue](https://github.com/prinzstani/CookieBot/issues/34).

**Comment by troycomi** [comment]
I think you may only be looking at the latest commit instead of the [overall diff](https://github.com/prinzstani/CookieBot/pull/40/files).

The idea is to have a pool of cookies saved to hit the max return on either a lucky cookie or (when get lucky is purchased) a lucky cookie during a frenzy, as brought up in issue #4.  The [handleSavings](https://github.com/prinzstani/CookieBot/pull/40/files#diff-06508d307c5682146eedd95eb3cac163R220) function calculates the value to save with some additional checks and scaling over time.

Buildings and upgrades are then purchased through the helper functions [below](https://github.com/prinzstani/CookieBot/pull/40/files#diff-06508d307c5682146eedd95eb3cac163R274) which basically only buy if there are enough savings.

Plants are purchased in a group to prevent cases where a cheap plant is continually bought and harvested without getting a chance to mutate with its more expensive partner.

For the particular case in issue #34 you still pass in the amount to buy and so it should work as intended.  In the auto savings mode, nothing is saved for the first 30 minutes, so it shouldn't affect the early game unless savings is set to lucky or lucky-frenzy.  Should I override those savings goals in the first 30 minutes as well?

The saving amount is a setting and can be disabled, though it currently defaults to auto.

**Comment by PrinzAndreas** [comment]
I understand now. In principle I agree with your changes, but there is the problem with the startup phase. As you say, the saving is not done in the beginning.
Still, you inserted the AutoPlay.buyBuilding(me, buyAmount); into handleBuildings. If you compare with the original code, you will see that the check is done against checkamount, while the buying is done with buyAmount. Currently, you do not use checkAmount.
This means in reality, the bot will try to buy 100 items of the building in the start phase, although it is only guaranteed that it is possible to buy 1. This will lead to the bot buying as many as possible up to 100. With your handling, it will buy 100 only when it is possible to buy 100, thereby reducing the number of buildings bought. In the start phase, it is essential to buy as many as possible and not wait until it is possible to buy 100.
I propose to scale the buyAmount depending on how many items can be bought of the most expensive building.
To your question: The handling of savings in relation to configuration is fine as it is now. No need to override for the first 30 minutes.

**Comment by troycomi** [comment]
I see, I thought checkAmount was for determining the best purchase, not the price.  Anyways, added another commit to take the checkAmount as input and should behave as before during the initial phase of the game.  Is that a reasonable fix?

I haven't tested after a fresh ascension but it is working on the early game.

**Comment by prinzstani** [comment]
Very good, thanks.

**Pull request merged**
