### PR TITLE
Various fixes

### LINKED ISSUE #97: In her likeness is too early
Do not get achievement "in her likeness" before we have bought at least one clone (achievement My own clone).

### LINKED ISSUE #103: Garden, bot not switching soil type after ascension and unlocking new soils
After my first ascension and reaching fertilizer again the bot didn't switch to it. I waited multiple ticks to see if it switched.
It is trying for bakeberries and looking at the bot code it should be using fertilizer for that, instead it stays on dirt.

it also seemed to have switched back to dirt after I manually set it to fertilizer at some point.

### PR DESCRIPTION
**Pull request by Kikithecat12345**
Closes #97.
Closes #103.

### CODE REVIEW

**Comment by Kikithecat12345** [comment]
I should make it such that meaty sugar lumps can't show up pre-grandmapocalypse.

**Comment by Kikithecat12345** [comment]
(ignore that force push. Just a `--amend` to change the title of the commit to something more descriptive.)

**Comment by Kikithecat12345** [comment]
Forgot to mark as draft, lol. 

Technically, this fixes #103. We should consider refactoring the entire strategy for the garden though, the code is a mess. I have made an issue for that.

**Review by prinzstani — APPROVED** [review]
Looks good.

**Comment by prinzstani** [comment]
I have created a new release from before your changes, so we can test a bit more before we run this into a full release.

**Comment by Kikithecat12345** [comment]
Works for me.
(Apologies for the chaos, it's been a while since I have programmed.)

**Pull request merged**
